In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report

In [3]:
df=pd.read_csv('Fish.csv')

In [4]:
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
y=df["Species"]
x=df.drop("Species",axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
knn.predict([[150,10,12,10,7,5]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Parkki'], dtype=object)

In [6]:
print(confusion_matrix(y_test,y_pred))

NameError: name 'confusion_matrix' is not defined

In [7]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       Bream       0.88      0.70      0.78        10
      Parkki       0.00      0.00      0.00         1
       Perch       0.44      0.89      0.59         9
        Pike       0.00      0.00      0.00         3
       Roach       0.00      0.00      0.00         1
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.62        32
   macro avg       0.33      0.37      0.34        32
weighted avg       0.55      0.62      0.57        32

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [9]:
print(accuracy_score(y_test,y_pred))
#print(recall_score(y_test,y_pred))
#print(precision_score(y_test,y_pred))

0.625

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [10]:
dd=pd.read_csv('titanic.csv')

In [11]:
dd

      pclass                                             name     sex      age  ...      fare    cabin embarked  survived
0          1                    Allen, Miss. Elisabeth Walton  female  29.0000  ...  211.3375       B5        S         1
1          1                   Allison, Master. Hudson Trevor    male   0.9167  ...  151.5500  C22 C26        S         1
2          1                     Allison, Miss. Helen Loraine  female   2.0000  ...  151.5500  C22 C26        S         0
3          1             Allison, Mr. Hudson Joshua Creighton    male  30.0000  ...  151.5500  C22 C26        S         0
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000  ...  151.5500  C22 C26        S         0
...      ...                                              ...     ...      ...  ...       ...      ...      ...       ...
1304       3                             Zabour, Miss. Hileni  female  14.5000  ...   14.4542      NaN        C         0
1305       3                            Zabour, Miss. Thamine  female      NaN  ...   14.4542      NaN        C         0
1306       3                        Zakarian, Mr. Mapriededer    male  26.5000  ...    7.2250      NaN        C         0
1307       3                              Zakarian, Mr. Ortin    male  27.0000  ...    7.2250      NaN        C         0
1308       3                               Zimmerman, Mr. Leo    male  29.0000  ...    7.8750      NaN        S         0

[1309 rows x 11 columns]

In [12]:
dd.isna().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [13]:
dd=dd.drop("cabin",axis=1)

In [14]:
dd['embarked']=dd.embarked.fillna(dd.embarked.mode()[0])

In [15]:
dd.isna().sum()

pclass        0
name          0
sex           0
age         263
sibsp         0
parch         0
ticket        0
fare          1
embarked      0
survived      0
dtype: int64

In [16]:
dd=dd.fillna(dd.mean(numeric_only=True))

In [17]:
dd.ticket

0        24160
1       113781
2       113781
3       113781
4       113781
         ...
1304      2665
1305      2665
1306      2656
1307      2670
1308    315082
Name: ticket, Length: 1309, dtype: object

In [18]:
dd=dd.drop(['name','ticket'],axis=1)

In [19]:
dd=pd.get_dummies(dd,drop_first=True)

In [20]:
dd.head()

   pclass      age  sibsp  parch      fare  survived  sex_male  embarked_Q  embarked_S
0       1  29.0000      0      0  211.3375         1     False       False        True
1       1   0.9167      1      2  151.5500         1      True       False        True
2       1   2.0000      1      2  151.5500         0     False       False        True
3       1  30.0000      1      2  151.5500         0      True       False        True
4       1  25.0000      1      2  151.5500         0     False       False        True

In [21]:
y=dd['survived']
x=dd.drop('survived',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)
knn=KNeighborsClassifier(n_neighbors=37)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      0.90      0.75       144
           1       0.76      0.40      0.52       118

    accuracy                           0.67       262
   macro avg       0.70      0.65      0.64       262
weighted avg       0.70      0.67      0.65       262