# UNIT_4_5_PQ_QB_VHA

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures

#### 215 For x = np.array([5, 15, 25, 35, 45, 55]) and y = np.array([5, 20, 14, 32, 22, 38]), apply simple linear regression using scikit learn library and calculate calculate R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

In [5]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape(6,1)
y = np.array([5, 20, 14, 32, 22, 38])
model=LinearRegression()
model.fit(x,y)
y_pred=model.predict(x)
print(r2_score(y_pred,y))
print(model.coef_)
print(model.intercept_)
for i in np.arange(5):
    print(model.predict(np.array([[i]])))

0.603109282121628
[0.54]
5.633333333333329
[5.63333333]
[6.17333333]
[6.71333333]
[7.25333333]
[7.79333333]

#### 216 Given a dataset with 'SAT' scores as independent variables and 'GPA' as the dependent variable,  calculate R squared, coeficient and intercept using linear regression and scikitlearn library. (Don't split data for training/testing)

In [6]:
df=pd.read_csv("SATGPA.csv")

In [7]:
df

     SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [8]:
x=df[["SAT"]]
y=df[["GPA"]]
model=LinearRegression()
model.fit(x,y)
y_pred=model.predict(x)
print(r2_score(y_pred,y))
print(model.coef_)
print(model.intercept_)

-0.46303043777421093
[[0.00165569]]
[0.2750403]

 217 Given a real estate price size year dataset, implement multiple linear regression using scikitlearn library. Using the model, make a prediction about an apartment price with size 750 sq.ft. for 2009.Also Calculate R squared, coeficient and intercept. (Don't split data for training/testing)

In [12]:
dd=pd.read_csv('real_estate.csv')
x=dd[['size','year']]
y=dd[['price']]
model=LinearRegression()
model.fit(x,y)
y_pred=model.predict(x)
print(r2_score(y_pred,y))
print(model.coef_)
print(model.intercept_)
print(model.predict(np.array([[750,2009]])))

0.7121374334888605
[[ 227.70085401 2916.78532684]]
[-5772267.01746328]
[[258330.34465995]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [11]:
dd

         price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

#### 218 Predict salary based on job position of 6.5 using polynomial regression  with a degree of 3 and scikit learn library for the given 'Position_Salaries.csv' dataset.  (Don't split data for training/testing)

In [13]:
df=pd.read_csv('Position_Salaries.csv')
x=df[["Level"]]
y=df[["Salary"]]
poly=PolynomialFeatures(degree=3)
x_poly=poly.fit_transform(x)
model=LinearRegression()
model.fit(x_poly,y)
y_pred=model.predict(x_poly)
print(r2_score(y_pred,y))
print(model.coef_)
print(model.intercept_)
print(model.predict(poly.transform(np.array([[6.5]]))))

0.9808499387901425
[[     0.         180664.33566432 -48548.95104895   4120.04662005]]
[-121333.33333331]
[[133259.46969697]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(

#### 219 For x = np.arange(0, 30) and y = np.array([3, 4, 5, 7, 10, 8, 9, 10, 10, 23, 27, 44, 50, 63, 67, 60, 62, 70, 75, 88, 81, 87, 95, 100, 108, 135, 151, 160, 169, 179]), apply polynomial regression using scikit learn library and calculate  R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

#### 220 "Write a program to make a model based on linear regression for the following dataframe created from a csv file named “Package.csv” of x and y which follows equation y = a + bx. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation.

#### 221 "Write a program to make a model based on linear regression for the following dataframe created from a csv file named “data.csv” of x1 and y which follows equation y = a+bx1. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation. Given Data in csv file:"

#### 222 "Write a program to create a Model using linear regression to predict the price of house using the csv file provided named “Housing.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

#### 223 "Write a program to create a Model using linear regression to predict the student scores using the csv file provided named “student_scores.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

#### 224 "Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “petrol_consumption.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

#### 225 Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error. (Wherever required remove null values, convert categorical data into numeric data) (Print Output wherever required)

# 226 "For the given RealEstate csv, write a python program satisfying following tasks to demonstrate application of machine learning through multiple linear regression as follows – 

Given: - 

Dataset                              RealEstate.csv

ML Library to be used    scikit-learn   

Dependent variable          'Y house price of unit area'

Independent variables     'X1 transaction date', 'X2 house age',  'X3 distance to the nearest MRT station', 'X4 number of 

convenience stores', 'X5 latitude' and  'X6 longitude'

1. Import required libraries.
2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
3. Remove ‘No’ column from the dataframe.
4. Check for any null values in features using appropriate method.
5. Create feature variables x and y as given above. 
6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
7. Create and fit regression model using appropriate method.
8. Use testing set created in step 6 to find and print the prediction of the outcome.
9. Find and print coefficient and mean squared error of the regression model."

In [14]:
df=pd.read_csv('RealEstate.csv')

In [15]:
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [16]:
df=df.drop('No',axis=1)

In [18]:
x=df.drop(["Y house price of unit area"],axis=1)
y=df[['Y house price of unit area']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=110)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(model.coef_)
print(model.intercept_)
print(r2_score(y_pred,y_test))
print(mean_squared_error(y_test,y_pred))

[[ 6.84308941e+00 -2.25466590e-01 -5.18046265e-03  1.12369103e+00
   1.87739728e+02 -4.29300312e+01]]
[-13203.67430063]
0.22374403332183235
77.14802598253691

#### 227 Write a program to create a Model using linear regression to predict the charges of insurance using the csv file provided named “insurance.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

#### 228 "Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”. Do the required process in the data before making a model. 

If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
Find co-efficient, intercept and mean squared error.

also Predict the quality of red wine for the following data:                       
fixed acidity: 8 

volatile acidity: 0.4       	

citric acid: 0.40                

residual sugar: 15          

chlorides: 0.048                  

free sulfur dioxide: 40      

total sulfur dioxide: 150     

density: 0.99                  

pH: 3                      

sulphates: 0.45                

alcohol: 10.5"

In [19]:
dr=pd.read_csv('winequality.csv')

In [20]:
dr

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  ...  density    pH  sulphates  alcohol  quality    Id
0               7.4             0.700         0.00             1.9      0.076                 11.0  ...  0.99780  3.51       0.56      9.4        5     0
1               7.8             0.880         0.00             2.6      0.098                 25.0  ...  0.99680  3.20       0.68      9.8        5     1
2               7.8             0.760         0.04             2.3      0.092                 15.0  ...  0.99700  3.26       0.65      9.8        5     2
3              11.2             0.280         0.56             1.9      0.075                 17.0  ...  0.99800  3.16       0.58      9.8        6     3
4               7.4             0.700         0.00             1.9      0.076                 11.0  ...  0.99780  3.51       0.56      9.4        5     4
...             ...               ...          ...             ...        ...                  ...  ...      ...   ...        ...      ...      ...   ...
1138            6.3             0.510         0.13             2.3      0.076                 29.0  ...  0.99574  3.42       0.75     11.0        6  1592
1139            6.8             0.620         0.08             1.9      0.068                 28.0  ...  0.99651  3.42       0.82      9.5        6  1593
1140            6.2             0.600         0.08             2.0      0.090                 32.0  ...  0.99490  3.45       0.58     10.5        5  1594
1141            5.9             0.550         0.10             2.2      0.062                 39.0  ...  0.99512  3.52       0.76     11.2        6  1595
1142            5.9             0.645         0.12             2.0      0.075                 32.0  ...  0.99547  3.57       0.71     10.2        5  1597

[1143 rows x 13 columns]

In [21]:
dr.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [22]:
dr.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [23]:
x=dr.drop(['quality','Id'],axis=1)
y=dr[['quality']]
model=LinearRegression()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(model.coef_)
print(model.intercept_)
print(r2_score(y_pred,y_test))
print(mean_squared_error(y_test,y_pred))
print(model.predict(np.array([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]])))

[[ 5.13430654e-02 -1.33625691e+00 -3.39100758e-01  4.12143173e-03
  -1.80653035e+00  1.88076181e-03 -2.28305818e-03 -3.06532562e+01
  -2.49236344e-01  9.73040097e-01  2.66586068e-01]]
[34.20980558]
-0.39626976768352695
0.38003245026277577
[[5.80087585]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

#### 229 "Consider variables x and y created from a pandas dataframe  “car.csv” . Create new column named “Age_car” (Age_car=2023-year)  For multiple linear regression problem, x contains the independent variables ( Age_car , Driven_kms , Fuel_Type , Selling_type , Transmission )  and y contains the dependent (Selling_Price) variable which is to be predicted.Write a Python program to spilt x and y into training and testing datasets with a 20% split. Then create a multiple linear regression model using the training data and print its coefficients ,intercept and mean squared error."

# 230 "Write a python program for following tasks - 
Make sure all the required libraries are imported at the beginning of the Jupyter Notebook.
a)	Load the windpower dataset into the notebook.

b)	Check records for any missing values and remove them permanently using appropriate method.

c)	Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and testing (25%) sets using random state of 42.

d)	Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.

e)	Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of 
determination) for each polynomial degree.

f)	Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot accordingly.

g)	Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.

h)	Print the coefficients and intercept for each trained polynomial regression model.

i)	Use each model to predict power output for wind speeds of 5, 10, 15, and 20 m/s, and print the predictions."